AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a VPC with public and private subnets, and an Internet Gateway.

Parameters:
  Prefix:
    Type: String
    Default: acs
    Description: Prefix for all resources

  VPCName:
    Type: String
    Default: vpc
    Description: Name of the VPC

  VPCCidrBlock:
    Type: String
    Default: 10.65.0.0/16
    Description: CIDR block for the VPC

  PublicSubnetName:
    Type: String
    Default: mgmt
    Description: Name of the public subnet

  PublicSubnetCidrBlock:
    Type: String
    Default: 10.65.1.0/24
    Description: CIDR block for the public subnet

  PrivateSubnetName:
    Type: String
    Default: guest
    Description: Name of the private subnet

  PrivateSubnetCidrBlock:
    Type: String
    Default: 10.65.2.0/24
    Description: CIDR block for the private subnet

Resources:
  RandomString:
    Type: 'AWS::CloudFormation::CustomResource'
    Properties:
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:RandomStringGenerator'

  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref VPCCidrBlock
      Tags:
        - Key: Name
          Value: !Sub '${Prefix}-${VPCName}-${RandomString}'

  PublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnetCidrBlock
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${Prefix}-${PublicSubnetName}-${RandomString}'

  PrivateSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnetCidrBlock
      Tags:
        - Key: Name
          Value: !Sub '${Prefix}-${PrivateSubnetName}-${RandomString}'

  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${Prefix}-igw-${RandomString}'

  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${Prefix}-public-rt-${RandomString}'

  PublicRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

Outputs:
  VPCId:
    Description: VPC ID
    Value: !Ref VPC

  PublicSubnetId:
    Description: Public Subnet ID
    Value: !Ref PublicSubnet

  PrivateSubnetId:
    Description: Private Subnet ID
    Value: !Ref PrivateSubnet

  InternetGatewayId:
    Description: Internet Gateway ID
    Value: !Ref InternetGateway
